name: Coverity Scan

on:
  push:
  pull_request:
# We only want to test official release code, not every pull request.
#  branches: [main]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - env:
      COVERITY_SCAN_EMAIL: ${{ secrets.COVERITY_SCAN_EMAIL }}
      COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    - uses: actions/checkout@v3
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}